[package]
name = "drogue-cloud-http-endpoint"
version = "0.2.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]

anyhow = "1"
snafu = "0.6"
async-trait = "0.1"

actix = "0.10"
actix-broker = "0.3.1"
actix-rt = "1.1"
actix-service = "1"
actix-tls = "2"
actix-web = "3"
actix-web-httpauth = "0.5.0"
actix-web-actors = "3"

futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"

envconfig = "0.9"

reqwest = { version = "0.10", features = ["json"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

uuid = { version = "0.8", features = ["v4"] }
percent-encoding = "2"
http = "0.2"

env_logger = "0.7"
log = "0.4"

cloudevents-sdk = "0.3"
cloudevents-sdk-actix-web = "0.3"

drogue-cloud-endpoint-common = { path = "../endpoint-common" }
drogue-cloud-service-api = { path = "../service-api" }
drogue-cloud-service-common = { path = "../service-common" }
drogue-ttn = "0.1.1"

dotenv = "0.15.0"
jsonwebtokens = "1.0.0-alpha.13"

awc = "2.0.0"

openid = "0.7"

[dependencies.rust-tls]
version = "0.19"
package = "rustls"

[dependencies.open-ssl]
version = "0.10"
package = "openssl"

[features]
default = ["openssl"]
openssl = ["actix-web/openssl"]
rustls = ["actix-web/rustls"]
