[package]
name = "drogue-cloud-endpoint-common"
version = "0.2.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]

actix = "0.10"
actix-broker = "0.3.1"
actix-web = "3"
actix-tls = { version = "2", optional = true }
reqwest = { version = "0.10", features = ["json"] }

anyhow = "1"
snafu = "0.6"
chrono = "0.4"

futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"

headers = "0.3"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

uuid = { version = "0.8", features = ["v4"] }

env_logger = "0.7"
log = "0.4"
envconfig = "0.9"

cloudevents-sdk = "0.3"
cloudevents-sdk-actix-web = "0.3"
cloudevents-sdk-reqwest = "0.3"

percent-encoding = "2"
base64 = "0.13"
http = "0.2"

openid = "0.7"

drogue-cloud-service-api = { path = "../service-api" }
drogue-cloud-service-common = { path = "../service-common" }

x509-parser = "0.9"
